describe('Cadastro de usuário', ()=>{
    beforeEach(() => {
        cy.visit('https://amzn.to/3EKqqQP')
        cy.title('have.value', 'Registro na Amazon')
      })

    it('Preenchendo campos com informações incorretas', ()=>{
        cy.get('div[class="a-row a-spacing-base"] input[type="text"]')
            .click()
            .type('Q`ayla Assurance',{delay:0})
            .should('have.value', 'Q`ayla Assurance')
        cy.get('.a-section input[type="email"]')
            .click()
            .type('qayla@gmail.com,br',{delay:0})
        cy.get('div[class="a-row a-spacing-base"] input[name="password"]')
            .click()
            .type('78945',{delay:0})
        cy.get('div[class="a-row a-spacing-base"] input[name="passwordCheck"]')
            .click()
            .type('54987{enter}',{delay:0})
        cy.get('.a-box-inner .a-alert-container .a-alert-content')
            .should('have.value', '')
            
    })
    it('Exibir mensagem de erro ao submeter o formulário sem preencher os campos obrigatórios', ()=>{
        cy.get('div[class="a-section a-spacing-extra-large"] span[class="a-button-inner"] input')
            .click()
        cy.get('.a-alert-container')
            .should('be.visible')
    })
    it('Preenchendo campos com informações corretas e validando', ()=>{
        cy.get('div[class="a-row a-spacing-base"] input[type="text"]')
            .click()
            .type('Q`ayla Assurance',{delay:0})
            .should('have.value', 'Q`ayla Assurance')
        cy.get('.a-section input[type="email"]')
            .click()
            .type('qayla@gmail.com.br',{delay:0})
        cy.get('div[class="a-row a-spacing-base"] input[name="password"]')
            .click()
            .type('789451',{delay:0})
        cy.get('div[class="a-row a-spacing-base"] input[name="passwordCheck"]')
            .click()
            .type('789451{shift}',{delay:0})
        cy.get('.a-box-inner .a-alert-container .a-alert-content')
            .should('have.value', '')
    })
})